# Default configuration for RKC HTTP Service

# Service Host and Port
host: "0.0.0.0" # Host for the FastAPI service (0.0.0.0 to be accessible externally)
port: 51001      # Port for the FastAPI service

# RKC Controller Settings
# IMPORTANT: Update serial_port to match your system (e.g., "/dev/ttyUSB0" on Linux)
serial_port: "COM3"         # Serial port for RKC controller
controller_address: "00"    # RKC controller address (as per your example)
baudrate: 19200             # Serial communication baudrate
timeout: 3                  # Serial communication timeout in seconds

# Polling Settings
polling_interval_seconds: 1 # How often to poll the RKC controller

# Logging Settings
log_file: "rkc_data.csv"    # Name of the log file
log_directory: "logs"       # Directory to store the log file (relative to src/rkc_controller_api)
max_history_lines: 1000      # Max number of lines to return for history endpoint

# RKC Identifiers (Verify these with your controller manual)
# These are used by the suggested methods in rkc_communication.py
# If you modify rkc_communication.py to use different identifiers, update them there.
# This section is more for informational purposes if not directly used by config loader.
rkc_identifiers:
  target_temperature_read: "S1" # Setpoint Value (Read)
  output_read: "O1" # Output Value 1
